travis:
  secure:
    BINSTAR_TOKEN: kISlBU2LJJCy0eZkkHkj+z1GsTe0LX3t79sXK4n69QtnhV288cCt5fnnEdo8xCFVAkfQ7R/1AR8IydDKuKl/irCeSme1T+vSd5lN837Nz7SLTIczNmdX7yOmMujD2IEErqGQyLqrVHlZK+QqBowNiFm4b5cZsNVGtaRASrE9LIfBzs25y43ujysvaBLzUviBTxAsKYJiLts84BXKup0qfWfQ3K3ay5jN8aakemNiUBZvLcHDOx4TgKZ2dS31gnbUnoB0q38S4yHJ4gzCGTTXGuPWbdyf5Fdj8Db9NapD/B5veLf8qoQGVPlLgy480jENw2rEScJBnctQB+QPaHl3XkbRcqK0d5W7NDbTTi7s2iXS6Iwr0Lu5XisUUgpp0c0SxAeRkRABAtF5511LwkJOhXBdrnR9IoZ9Zt3MB4SysxwharNHiZ3aI0M29sA5taja4WXibXkuZUboSiSeDsmwbPR2EQDVYlKpzBYiJ3lCDp8aWtkzwmNrULv8TyKTt2nBODx0TzWl50dcRB3rd4jjBSzhwpMUB8D0Gprt8Chb2urY4elEFUP92GG6Vpp7zxlzTQyqEymKUdMoIbfkQiP4Tt+fraIWjslXqNLsMAWpSdESMunOGdLvhwaF2q9fWxt/1mHoeiQMvrWld/rL75TkNpsBecuukz2mO/e+ihrZN7o=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
